const menu=document.querySelector('.menu-toggle');const mobileNav=document.querySelector('#mobile-nav');menu.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));menu.setAttribute('aria-label',expanded?'Открыть меню':'Закрыть меню');mobileNav.hidden=expanded;});mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileNav.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Открыть меню');}));
const programs={vocal:{title:'Вокал',description:'Найди своё звучание и развивай голос. Программы для начинающих и опытных исполнителей.',items:['Эстрадно-джазовый вокал','Экстрим-вокал','Народный и академический вокал','Вокальная техника SLS: дыхание, опора, диапазон'],choice:'Вокал'},instruments:{title:'Инструментальное исполнительство',description:'Освой любимый инструмент или продолжи музыкальное образование с опытными педагогами.',items:['Фортепиано и основы импровизации','Гитара и бас-гитара','Ударные инструменты','Скрипка и саксофон'],choice:'Инструментальное исполнительство'},composition:{title:'Композиция и аранжировка',description:'Основы композиции и аранжировки — направление предпрофессиональной программы Академии Музыки и Голоса.',items:['Для учеников с начальной и базовой музыкальной подготовкой','Развитие авторского музыкального мышления','Индивидуальный подход к творческим целям'],choice:'Композиция и аранжировка'},stage:{title:'Сценическое мастерство',description:'Обрети уверенность на сцене, развивай артистизм и умение общаться со зрителем.',items:['Техника публичных выступлений','Актёрское и сценическое мастерство','Развитие артистизма','Практика в концертах и творческих проектах'],choice:'Сценическое мастерство'},children:{title:'Музыка для детей',description:'Знакомство с музыкой и творчеством. В академии есть курсы для детей от 4 лет.',items:['Вокал для детей от 4 лет','Знакомство с музыкой: скрипка, фортепиано, гитара','Игровой английский для детей'],choice:'Музыка для детей'}};
const programDialog=document.querySelector('#program-dialog');const applicationDialog=document.querySelector('#application-dialog');let selectedProgram='';
document.querySelectorAll('[data-program]').forEach(button=>button.addEventListener('click',()=>{const p=programs[button.dataset.program];selectedProgram=p.choice;document.querySelector('#program-dialog-title').textContent=p.title;document.querySelector('#program-dialog-description').textContent=p.description;document.querySelector('#program-dialog-list').replaceChildren(...p.items.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));programDialog.showModal();}));
function openApplication(choice=''){document.querySelector('#application-form').reset();document.querySelector('#email-ready').hidden=true;if(choice)applicationDialog.querySelector('select').value=choice;applicationDialog.showModal();}
document.querySelectorAll('[data-apply]').forEach(b=>b.addEventListener('click',()=>openApplication()));document.querySelector('#program-apply').addEventListener('click',()=>{programDialog.close();openApplication(selectedProgram);});
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close();}});});
const tabs=[...document.querySelectorAll('[role=tab]')];function activateTab(tab){tabs.forEach(t=>{const active=t===tab;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!active;});}tabs.forEach((t,i)=>{t.addEventListener('click',()=>activateTab(t));t.addEventListener('keydown',e=>{let target;if(e.key==='ArrowRight'||e.key==='ArrowLeft')target=tabs[(i+1)%tabs.length];if(e.key==='Home')target=tabs[0];if(e.key==='End')target=tabs[tabs.length-1];if(target){e.preventDefault();activateTab(target);target.focus();}});});
document.querySelectorAll('.gallery-image').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#lightbox-image').src=b.dataset.photo;document.querySelector('#lightbox-image').alt=b.dataset.caption;document.querySelector('#lightbox-caption').textContent=b.dataset.caption;document.querySelector('#image-dialog').showModal();}));
document.querySelector('#application-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const text=`Здравствуйте! Хочу узнать об обучении в Академии Музыки и Голоса.\n\nИмя: ${String(f.get('name')).trim()}\nКонтакт: ${String(f.get('contact')).trim()}\nНаправление: ${f.get('program')}\n\nПожалуйста, расскажите о программе, расписании и стоимости обучения.`;document.querySelector('#email-text').value=text;document.querySelector('#email-ready').hidden=false;location.href='mailto:jazzvidal20@gmail.com?subject='+encodeURIComponent('Заявка на обучение — 2026–2027')+'&body='+encodeURIComponent(text);});
document.querySelector('#copy-application').addEventListener('click',async e=>{const field=document.querySelector('#email-text');try{await navigator.clipboard.writeText(field.value);e.target.textContent='Текст скопирован';}catch{field.focus();field.select();e.target.textContent='Выделено — нажми «Копировать»';}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!mobileNav.hidden){mobileNav.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Открыть меню');menu.focus();}});
